/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class Grafica extends javax.swing.JPanel {
     Restaurant r;
     int cont=0;
    /**
     * Creates new form Grafica
     */
    public Grafica(Restaurant R) {
        initComponents();
        this.r=R;
    }

    public Restaurant getF() {
        return r;
    }

    public void setF(Restaurant r) {
        this.r = r;
    }

    public Restaurant getR() {
        return r;
    }

    public void setR(Restaurant r) {
        this.r = r;
    }

    public int getCont() {
        return cont;
    }

    public void setCont(int cont) {
        this.cont = cont;
    }

    public JLabel getEntradas() {
        return Entradas;
    }

    public void setEntradas(JLabel Entradas) {
        this.Entradas = Entradas;
    }

    public JLabel getFuertes() {
        return Fuertes;
    }

    public void setFuertes(JLabel Fuertes) {
        this.Fuertes = Fuertes;
    }

    public JLabel getOrdenes() {
        return Ordenes;
    }

    public void setOrdenes(JLabel Ordenes) {
        this.Ordenes = Ordenes;
    }

    public JLabel getPostres() {
        return Postres;
    }

    public void setPostres(JLabel Postres) {
        this.Postres = Postres;
    }

    public JLabel getCerradas() {
        return Cerradas;
    }

    public void setCerradas(JLabel Cerradas) {
        this.Cerradas = Cerradas;
    }

    public JLabel getCantidadE() {
        return CantidadE;
    }

    public void setCantidadE(JLabel CantidadE) {
        this.CantidadE = CantidadE;
    }

    public JLabel getCantidadF() {
        return CantidadF;
    }

    public void setCantidadF(JLabel CantidadF) {
        this.CantidadF = CantidadF;
    }

    public JLabel getCantidadP() {
        return CantidadP;
    }

    public void setCantidadP(JLabel CantidadP) {
        this.CantidadP = CantidadP;
    }

    public JLabel getCantidadM() {
        return CantidadM;
    }

    public void setCantidadM(JLabel CantidadM) {
        this.CantidadM = CantidadM;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entradas = new javax.swing.JLabel();
        Fuertes = new javax.swing.JLabel();
        Postres = new javax.swing.JLabel();
        Ordenes = new javax.swing.JLabel();
        Cerradas = new javax.swing.JLabel();
        CantidadE = new javax.swing.JLabel();
        CantidadF = new javax.swing.JLabel();
        CantidadP = new javax.swing.JLabel();
        CantidadM = new javax.swing.JLabel();

        Entradas.setText("jLabel1");

        Fuertes.setText("jLabel1");

        Postres.setText("jLabel1");

        Ordenes.setText("jLabel1");

        Cerradas.setText("jLabel1");

        CantidadE.setText("jLabel1");

        CantidadF.setText("jLabel2");

        CantidadP.setText("jLabel3");

        CantidadM.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CantidadM)
                    .addComponent(CantidadP)
                    .addComponent(CantidadF)
                    .addComponent(CantidadE)
                    .addComponent(Ordenes)
                    .addComponent(Postres)
                    .addComponent(Fuertes)
                    .addComponent(Entradas))
                .addGap(170, 170, 170)
                .addComponent(Cerradas)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(CantidadE)
                .addGap(18, 18, 18)
                .addComponent(CantidadF)
                .addGap(18, 18, 18)
                .addComponent(CantidadP)
                .addGap(18, 18, 18)
                .addComponent(CantidadM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(Entradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fuertes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Postres)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ordenes)
                    .addComponent(Cerradas))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadE;
    private javax.swing.JLabel CantidadF;
    private javax.swing.JLabel CantidadM;
    private javax.swing.JLabel CantidadP;
    private javax.swing.JLabel Cerradas;
    private javax.swing.JLabel Entradas;
    private javax.swing.JLabel Fuertes;
    private javax.swing.JLabel Ordenes;
    private javax.swing.JLabel Postres;
    // End of variables declaration//GEN-END:variables
}
