/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class Grafica extends javax.swing.JPanel {
     Restaurant r;
     int cont=0;
    /**
     * Creates new form Grafica
     */
    public Grafica(Restaurant R) {
        initComponents();
        this.r=R;
    }

    public Restaurant getF() {
        return r;
    }

    public void setF(Restaurant r) {
        this.r = r;
    }

    public Restaurant getR() {
        return r;
    }

    public void setR(Restaurant r) {
        this.r = r;
    }

    public int getCont() {
        return cont;
    }

    public void setCont(int cont) {
        this.cont = cont;
    }

    public JLabel getEntradas() {
        return Entradas;
    }

    public void setEntradas(JLabel Entradas) {
        this.Entradas = Entradas;
    }

    public JLabel getFuertes() {
        return Fuertes;
    }

    public void setFuertes(JLabel Fuertes) {
        this.Fuertes = Fuertes;
    }

    public JLabel getOrdenes() {
        return Ordenes;
    }

    public void setOrdenes(JLabel Ordenes) {
        this.Ordenes = Ordenes;
    }

    public JLabel getPostres() {
        return Postres;
    }

    public void setPostres(JLabel Postres) {
        this.Postres = Postres;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entradas = new javax.swing.JLabel();
        Fuertes = new javax.swing.JLabel();
        Postres = new javax.swing.JLabel();
        Ordenes = new javax.swing.JLabel();

        Entradas.setText("jLabel1");

        Fuertes.setText("jLabel1");

        Postres.setText("jLabel1");

        Ordenes.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ordenes)
                    .addComponent(Postres)
                    .addComponent(Fuertes)
                    .addComponent(Entradas))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(Entradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fuertes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Postres)
                .addGap(60, 60, 60)
                .addComponent(Ordenes)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Entradas;
    private javax.swing.JLabel Fuertes;
    private javax.swing.JLabel Ordenes;
    private javax.swing.JLabel Postres;
    // End of variables declaration//GEN-END:variables
}
